ar3:
    # Publish all joint states -----------------------------------
  ar3_joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  ar3_joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_1
    pid: {p: 100.0, i: 0.01, d: 10.0}
  ar3_joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_2
    pid: {p: 100.0, i: 0.01, d: 10.0}
  ar3_joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_3
    pid: {p: 100.0, i: 0.01, d: 10.0}
  ar3_joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_4
    pid: {p: 100.0, i: 0.01, d: 10.0}
  ar3_joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_5
    pid: {p: 100.0, i: 0.01, d: 10.0}
  ar3_joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_6
    pid: {p: 100.0, i: 0.01, d: 10.0}
  # joint7为fix关节

  ar3_joint8_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_8
    pid: {p: 100.0, i: 0.01, d: 10.0}
  ar3_joint9_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_9
    pid: {p: 100.0, i: 0.01, d: 10.0}
